#pragma once

#include <QtGlobal>

#if defined(CONNECTEDCREATORPLUGIN_LIBRARY)
#  define CONNECTEDCREATORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONNECTEDCREATORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif
